 const classic = [
    { name: 'Black Russian', category: 'classic', base: 'vodka', volume: 'short', taste: 'sweet', time: 'digestif'},
    { name: 'Bloody Mary', category: 'classic', base: 'vodka', volume: 'long', taste: 'spicy', time: 'anytime'},
    { name: 'Cosmopolitan', category: 'classic', base: 'vodka', volume: 'short', taste: 'sour', time: 'anytime'},
    { name: 'Cuba libre', category: 'classic', base: 'rum', volume: 'long', taste: 'sweet', time: 'anytime'},
    { name: 'French 75', category: 'classic', base: 'gin', volume: 'short', taste: 'citrus', time: 'anytime'},
    { name: 'Hemingway Special', category: 'classic', base: 'rum', volume: 'short', taste: 'citrus', time: 'anytime'},
    { name: 'Horses Neck', category: 'classic', base: 'cognac', volume: 'long', taste: 'spicy', time: 'anytime'},
    { name: 'Irish coffee', category: 'classic', base: 'whiskey', volume: 'short', taste: 'sweet', time: 'anytime'},
    { name: 'Long Island iced tea', base: 'vodka', volume: 'long', taste: 'sweet', time: 'anytime'},
    { name: 'Mai Tai', category: 'classic', base: 'rum', volume: 'long', taste: 'sour', time: 'anytime'},
    { name: 'Margarita', category: 'classic', base: 'tequila', volume: 'short', taste: 'citrus', time: 'anytime'},
    { name: 'Mint julep', category: 'classic', base: 'whiskey', volume: 'short', taste: 'sweet', time: 'anytime'},
    { name: 'Mojito', category: 'classic', base: 'rum', volume: 'long', taste: 'sour', time: 'anytime'},
    { name: 'Moscow mule', category: 'classic', base: 'vodka', volume: 'short', taste: 'sour', time: 'anytime'},
    { name: 'Pina Colada', category: 'classic', base: 'rum', volume: 'long', taste: 'sweet', time: 'anytime'},
    { name: 'See Breeze', category: 'classic', base: 'vodka', volume: 'long', taste: 'citrus', time: 'anytime'},
    { name: 'Sex on the Beach', category: 'classic', base: 'vodka', volume: 'long', taste: 'sweet', time: 'anytime'},
    { name: 'Singapore Sling', category: 'classic', base: 'gin', volume: 'long', taste: 'spicy', time: 'anytime'},
    { name: 'Tequila Sunrise', category: 'classic', base: 'tequila', volume: 'long', taste: 'sweet', time: 'anytime'},
    { name: 'Vesper', category: 'classic', base: 'gin', volume: 'short', taste: 'bitter', time: 'anytime'},
    { name: 'Zombie', category: 'classic', base: 'rum', volume: 'long', taste: 'sour', time: 'anytime'}
];

 const unforgattables = [
    { name: 'Aviation', category: 'unfog', base: 'gin', volume: 'long', taste: 'sour', time: 'anytime'},
    { name: 'Alexander', category: 'unfog', base: 'cognac', volume: 'long', taste: 'sweet', time: 'digestif'},
    { name: 'White Lady', category: 'unfog', base: 'gin', volume: 'short', taste: 'citrus', time: 'anytime'},
    { name: 'Brandy Alexander', category: 'unfog', base: 'cognac', volume: 'long', taste: 'sweet', time: 'anytime'},
    { name: 'Boulevardier', category: 'unfog', base: 'whiskey', volume: 'long', taste: 'bitter', time: 'aperitif'},
    { name: 'Whiskey sour', category: 'unfog', base: 'whiskey', volume: 'long', taste: 'sour', time: 'aperitif'},
    { name: 'Monkey Gland', category: 'unfog', base: 'gin', volume: 'long', taste: 'citrus', time: 'anytime'},
    { name: 'Dayquiri', category: 'unfog', base: 'rum', volume: 'long', taste: 'citrus', time: 'aperitif'},
    { name: 'Ginn Fizz', category: 'unfog', base: 'gin', volume: 'long', taste: 'citrus', time: 'anytime'},
    { name: 'John Collinz', category: 'unfog', base: 'gin', volume: 'long', taste: 'citrus', time: 'anytime'},
    { name: 'Casino', category: 'unfog', base: 'gin', volume: 'long', taste: 'citrus', time: 'anytime'},
    { name: 'Clover Club', category: 'unfog', base: 'gin', volume: 'long', taste: 'sweet', time: 'anytime'},
    { name: 'Angel Face', category: 'unfog', base: 'gin', volume: 'long', taste: 'sweet', time: 'anytime'},
    { name: 'Manhattan', category: 'unfog', base: 'whiskey', volume: 'long', taste: 'sweet', time: 'aperitif'},
    { name: 'Dry Martini', category: 'unfog', base: 'gin', volume: 'long', taste: 'bitter', time: 'anytime'},
    { name: 'Between the Sheets', category: 'unfog', base: 'rum', volume: 'long', taste: 'citrus', time: 'anytime'},
    { name: 'Mary Pickford', category: 'unfog', base: 'rum', volume: 'long', taste: 'sweet', time: 'anytime'},
    { name: 'Negroni', category: 'unfog', base: 'gin', volume: 'long', taste: 'bitter', time: 'aperitif'},
    { name: 'Old Fashioned', category: 'unfog', base: 'whiskey', volume: 'long', taste: 'citrus', time: 'aperitif'},
    { name: 'Paradise', category: 'unfog', base: 'gin', volume: 'long', taste: 'citrus', time: 'anytime'},
    { name: 'Planters Punch', category: 'unfog', base: 'rum', volume: 'long', taste: 'sweet', time: 'anytime'},
    { name: 'Ramos gin fizz', category: 'unfog', base: 'gin', volume: 'long', taste: 'sour', time: 'anytime'},
    { name: 'Rusty Nail', category: 'unfog', base: 'whiskey', volume: 'long', taste: 'sweet', time: 'digestif'},
    { name: 'Sazerac', category: 'unfog', base: 'cognac', volume: 'long', taste: 'sweet', time: 'digestif'},
    { name: 'Sidecar', category: 'unfog', base: 'cognac', volume: 'long', taste: 'citrus', time: 'anytime'},
    { name: 'Stinger', category: 'unfog', base: 'cognac', volume: 'long', taste: 'sweet', time: 'digestif'}
];

 const newEra = [
    { name: 'Barracuda', category: 'newEra', base: 'rum', volume: 'long', taste: 'sweet', time: 'anytime'},
    { name: 'Bees Knees', category: 'newEra', base: 'gin', volume: 'short', taste: 'citrus', time: 'anytime'},
    { name: 'Bramble', category: 'newEra', base: 'gin', volume: 'short', taste: 'sour', time: 'anytime'},
    { name: 'Fernandito', category: 'newEra', base: 'gin', volume: 'long', taste: 'sweet', time: 'anytime'},
    { name: 'French martini', category: 'newEra', base: 'vodka', volume: 'short', taste: 'sweet', time: 'anytime'},
    { name: 'Illegal', category: 'newEra', base: 'rum', volume: 'short', taste: 'sour', time: 'anytime'},
    { name: 'Lemon drop martini', category: 'newEra', base: 'vodka', volume: 'short', taste: 'citrus', time: 'anytime'},
    { name: 'New York Sour', category: 'newEra', base: 'whiskey', volume: 'short', taste: 'sour', time: 'anytime'},
    { name: 'Old Cuban', category: 'newEra', base: 'rum', volume: 'short', taste: 'citrus', time: 'anytime'},
    { name: 'Paloma', category: 'newEra', base: 'tequila', volume: 'long', taste: 'citrus', time: 'anytime'},
    { name: 'Paper Plane', category: 'newEra', base: 'whiskey', volume: 'short', taste: 'sour', time: 'aperitif'},
    { name: 'Penicillin', category: 'newEra', base: 'whiskey', volume: 'short', taste: 'bitter', time: 'anytime'},
    { name: 'Russian Spring Punch', category: 'newEra', base: 'vodka', volume: 'long', taste: 'sour', time: 'anytime'},
    { name: 'Southside', category: 'newEra', base: 'gin', volume: 'short', taste: 'sour', time: 'anytime'},
    { name: 'Spicy Fifty', category: 'newEra', base: 'vodka', volume: 'short', taste: 'spicy', time: 'anytime'},
    { name: 'Suffering Bastard', category: 'newEra', base: 'cognac', volume: 'long', taste: 'bitter', time: 'anytime'},
    { name: 'Tipperary', category: 'newEra', base: 'whiskey', volume: 'short', taste: 'bitter', time: 'anytime'},
    { name: 'Tommys margarita', category: 'newEra', base: 'tequila', volume: 'short', taste: 'citrus', time: 'anytime'},
    { name: 'Trinidad sour', category: 'newEra', base: 'whiskey', volume: 'short', taste: 'bitter', time: 'anytime'},
    { name: 'Yellow Bird', category: 'newEra', base: 'rum', volume: 'short', taste: 'sour', time: 'anytime'}
];
